# frozen_string_literal: true
#
# Generic rake tasks for cl-sap-udfs-ruby. Load these from the consuming
# product's own Rakefile, e.g.:
#
#   Dir[Rails.root.join("vendor/clavisco/sap_udfs/lib/tasks/*.rake")].each { |f| load f }
#
# All sap:schema:* / sap:test_data:* tasks take the path to a "connections
# file" as an argument: a JSON array, one entry per SAP company to run
# against (base_url, company_db, username, password, optional name). One
# entry for a single-company product, N for a multi-company client. How
# that file is built (by hand today, generated by a pipeline tomorrow) and
# where it lives is entirely up to the product — these tasks only read it,
# and it must never be committed (real credentials).
#
# The consuming product must have Clavisco::ServiceLayer::Client on the
# load path already (this gem does not depend on it directly).

require_relative "../clavisco/sap_udfs"

namespace :sap do
  namespace :schema do
    desc "Preview UDT/UDF changes across every company in the connections file (dry-run, no writes). Optional csv_path writes a CSV report."
    task :diff, [:connections_file, :csv_path] do |_, args|
      Clavisco::SapUdfs::RakeSupport.diff(args[:connections_file], args[:csv_path])
    end

    desc "Apply UDT/UDF sync across every company in the connections file. Optional csv_path writes a CSV report."
    task :sync, [:connections_file, :csv_path] do |_, args|
      Clavisco::SapUdfs::RakeSupport.sync(args[:connections_file], args[:csv_path])
    end

    desc "Apply UDT/UDF sync for a single schema, across every company in the connections file. Optional csv_path writes a CSV report."
    task :sync_one, [:schema_name, :connections_file, :csv_path] do |_, args|
      Clavisco::SapUdfs::RakeSupport.sync_one(args[:schema_name], args[:connections_file], args[:csv_path])
    end

    desc "Check config/sap_schemas against the sync lock for drift (no SAP calls)"
    task :check_lock do
      Clavisco::SapUdfs::RakeSupport.check_lock
    end
  end

  namespace :test_data do
    desc "Insert seed rows (from a JSON file) into a UDT, across every company in the connections file"
    task :seed, [:connections_file, :seed_file] do |_, args|
      Clavisco::SapUdfs::RakeSupport.seed(args[:connections_file], args[:seed_file])
    end

    desc "Query rows from a UDT, across every company in the connections file"
    task :query, [:connections_file, :table_name, :filter] do |_, args|
      Clavisco::SapUdfs::RakeSupport.query(args[:connections_file], args[:table_name], args[:filter])
    end
  end
end
