# frozen_string_literal: true

require "json"

module Clavisco
  module SapUdfs
    # Reads and validates the connections file: a JSON array where each entry
    # carries what's needed to build one Clavisco::ServiceLayer::Client.
    #
    # One entry = one SAP company. A client with 4 companies just lists 4;
    # a single-company product lists 1. How the file gets built (by hand
    # today, generated by a pipeline later) is entirely up to the consuming
    # product — this module only reads and validates it.
    #
    # Shape:
    # [
    #   { "name": "ACME_PROD", "base_url": "https://...", "company_db": "...",
    #     "username": "...", "password": "..." },
    #   ...
    # ]
    # "name" is optional (defaults to company_db) — used only to label
    # results/errors when reporting per company, not for any logic.
    module Connections
      REQUIRED_KEYS = %w[base_url company_db username password].freeze

      def self.load(path)
        raise "Connections file not found: #{path}" if path.to_s.strip.empty? || !File.exist?(path)

        raw = JSON.parse(File.read(path))
        raise "Connections file must contain a JSON array, got #{raw.class}" unless raw.is_a?(Array)
        raise "Connections file is empty — at least one connection is required" if raw.empty?

        raw.each_with_index.map { |entry, i| validate!(entry, i) }
      end

      def self.validate!(entry, index)
        raise "Connection ##{index} must be a JSON object" unless entry.is_a?(Hash)

        missing = REQUIRED_KEYS.reject { |k| entry[k].to_s.strip != "" }
        raise "Connection ##{index} is missing required field(s): #{missing.join(', ')}" unless missing.empty?

        {
          name: entry["name"] || entry["company_db"],
          base_url: entry["base_url"],
          company_db: entry["company_db"],
          username: entry["username"],
          password: entry["password"],
          session_owner_id: entry["session_owner_id"]
        }
      end
    end
  end
end
